### ISSUE TITLE
Y9000K2021(7i)

### ISSUE THREAD

**Issue by EXCADOGOD** [SmokelessCPUv2/SmokelessRuntimeEFIPatcher#1]
I used it but did't have the bios choose, I can see some things was runing,but nothing happened in my bios(48ww)

**Comment by EXCADOGOD** [comment]
I use this code, and it was running, but when I go to bios nothing was happened
Op Loaded
H2OFormBrowserDxe
Op Patch
Pattern
59B963B8C60E334099C18FD89F04022200000000
59B963B8C60E334099C18FD89F04022201000000
Op Patch
Pattern
E33545B0043046499EB714942898305300000000
E33545B0043046499EB714942898305301000000
Op Patch
Pattern
732871A65F92C64690B4A40F86A0917B00000000
732871A65F92C64690B4A40F86A0917B01000000
Op Patch
Pattern
9E76D4C6487F2A4D98E987ADCCF35CCC00000000
9E76D4C6487F2A4D98E987ADCCF35CCC01000000
Op End

Op LoadFromFV
SetupUtilityApp
Op Exec

**Comment by SmokelessCPUv2** [comment]
Give a try with the 2022 config, if not will see what we can do

**Comment by EXCADOGOD** [comment]
2022 config also not useful, maybe the 2021 intel 48ww was defferent with 45 and 47ww

**Comment by SmokelessCPUv2** [comment]
Try this, also I saw that you are in the discord, feel free to reply there, will get back when I have time


Op Loaded
H2OFormBrowserDxe
Op Patch
Pattern
732871A65F92C64690B4A40F86A0917B00000000
732871A65F92C64690B4A40F86A0917B01000000
Op Patch
Pattern
9E76D4C6487F2A4D98E987ADCCF35CCC00000000
9E76D4C6487F2A4D98E987ADCCF35CCC01000000
Op Patch
Pattern
1AB0E0C17E60754BB8BB0631ECFAACF200000000
1AB0E0C17E60754BB8BB0631ECFAACF201000000
Op End

Op LoadFromFV
SetupUtilityApp
Op Exec

**Comment by EXCADOGOD** [comment]
Think you, this was useful,
