### ISSUE TITLE
Legion T5 26AMR5 bios unlock

### ISSUE THREAD

**Issue by Rene0220** [SmokelessCPUv2/SmokelessRuntimeEFIPatcher#2]
How i can unlock Legion T5 26AMR5(r5 3600, 3060ti, BIOS:O4MKT25A)? I very need xmp profile.

**Comment by SmokelessCPUv2** [comment]
This is not a request form,
Try asking on the discord server.
Please put some effor in it, I/we will not make any patch if you are not willing to put any effor in it.

So at least make a question, specifiing the bios vendor, provide a link to a dump, and what you have tryed.

That said, if not wrong no xmp/docp is available, but if you want give a shot, feel free.

Also before patching, try if the UniversalAmdFormBrowser work, as is the simpler way to access AMD menu
