### ISSUE TITLE
Sorry man can you help please? 

### ISSUE THREAD

**Issue by kamyd** [SmokelessCPUv2/SmokelessRuntimeEFIPatcher#3]
Hi Thank you for this.
I stupidly change my ram speed higher than normal and my laptop won't boot no matter what. The things that I tried: (all with and without ssd)
1-Removed battery and cmos battery for 15 minutes.
2-Testing with 3 different rams. 
3-i made a fat32 flash drive with bios file as it was said it winraid, put flash drive in and pressed fn+r then connected power cable and booted it up but it wont beep and just keeps restarting after a minute or two.

Tried this with different names, flash, port, with battery and no battery. 
My bios is h1cn and its intel legion 5 11800h

Can you help me please?

Is this the bios chip?
![IMG_20221023_133335](https://user-images.githubusercontent.com/49566563/197388121-7884ffb4-34e8-432b-9b53-e88b92e0f9c1.jpg)

**Comment by SmokelessCPUv2** [comment]
I'm tempted to just close this issue with: "Not my fault and not related my tool fault":,
but join Legion Series Discord (https://discord.com/invite/legionseries)
and ping me (SmokelessCPU#9368) in the #bios-fd channel
