### ISSUE TITLE
Hello. Does this work with other H2O BIOSes? I try to use on clevo 2022 model. Change Suppress If.

### ISSUE THREAD

**Issue by cbbos** [SmokelessCPUv2/SmokelessRuntimeEFIPatcher#4]
Hello. Does this work with other H2O BIOSes? I try to use on clevo 2022 model. Change Suppress If.
`Op Loaded
SetupUtility
Op Patch
Pattern
1206901800000F0F5A0A020004000000FFFF008305
4706901800000F0F5A0A020004000000FFFF008305
Op End

Op LoadFromFV
SetupUtilityApp
Op Exec`
The program returns an error:Failed on Opening SREP_Config : Not Found

**Comment by SmokelessCPUv2** [comment]
Are you sure you named the config file correctly?

**Comment by cbbos** [comment]
Maybe doing something wrong? Here I am using the pattern you provided. I changed the module name and content

**Comment by SmokelessCPUv2** [comment]
Can you post a screenshot of you usb?

**Comment by cbbos** [comment]
Do you need a [screenshot of the root directory?](https://photos.app.goo.gl/eSwdXASs3QccsMWGA) Or a usb device snapshot? (It's a pretty normal 16GB storage device).

**Comment by SmokelessCPUv2** [comment]
You have the wrong config file name, you have a n in excess, is config not confing

**Comment by cbbos** [comment]
Yes. I realized my mistake. Thanks for the quick response.
