### ISSUE TITLE
How to load a non-HXHS AOD_SETUP menu

### ISSUE THREAD

**Issue by NaG1Ane** [SmokelessCPUv2/SmokelessRuntimeEFIPatcher#5]
How to load  non HX HS AOD_SETUP menu 
My laptop is ROG FLOW X13 R7-5800HS 
AMD Load AOD menu for R9 HS 
Cannot be load on R7 HS

**Comment by SmokelessCPUv2** [comment]
Even if we load it is useless, as the setting are ignored...

**Comment by NaG1Ane** [comment]
Even use ch341a programmer flash mod bios？
I have modified most of the varstore options ，spread spectrum  clock gating   fclk mclk uclk
But i can't get more curve voltage  improve efficiency 
Cezanne efficiency is worse at 35w

**Comment by SmokelessCPUv2** [comment]
1) just modifing the var store for shit like memory or fabric, are not working, the require modify from the ui, as this will commit some psp change...

2) all there are available under cbs

3) anything related to voltage will be ignored by the smu anyway...
