### ISSUE TITLE
How to overclock R9-6900HX and DDR5 memory in the UniversalAMDFormBrowser?

### ISSUE THREAD

**Issue by MJYlunar** [SmokelessCPUv2/SmokelessRuntimeEFIPatcher#6]
Hi bro, my device is ROG laptop G513RW, CPU is R9-6900hx, and the platform is DDR5. After using the UniversalAMDFormBrowser released by you to enter the hidden bios, I found that the interface inside is very different from that of DDR4 platform.
Would you like to know how you can overclock CPU and memory in the UniversalAMDFormBrowser for DDR5, or does UniversalAMDFormBrowser not work on DDr5? 
Thank you for your advice.

**Comment by SmokelessCPUv2** [comment]
I have no direct experience with anything newer than renoir (4000 series).

But universalformbrowser, is just an ui, all the setting that it show are loaded from the one that agesa/amd bioa exported, so if they have changed is cause amd changed...

But i have no idea if they work or not.
Is up to you to test
